### ISSUE TITLE
Error about data loading

### ISSUE THREAD

**Issue by small-beebee** [charlesCXK/SA-Gate#13]
root@47cc999396b9:/mnt/txf/codes/SA-Gate/RGBD_Semantic_Segmentation_PyTorch/model/SA-Gate.nyu.432# python -m torch.distributed.launch --nproc_per_node=$NGPUS train.py
19 04:15:06 PyTorch Version 1.0.0, Furnace Version 0.1.1
19 04:15:06 PyTorch Version 1.0.0, Furnace Version 0.1.1
19 04:15:07 WRN A exception occurred during Engine initialization, give up running process
Traceback (most recent call last):
  File "train.py", line 64, in <module>
    norm_layer=BatchNorm2d)
  File "/mnt/txf/codes/SA-Gate/RGBD_Semantic_Segmentation_PyTorch/model/SA-Gate.nyu.432/network.py", line 33, in __init__
    deep_stem=True, stem_width=64)
  File "/mnt/txf/codes/SA-Gate/RGBD_Semantic_Segmentation_PyTorch/model/SA-Gate.nyu.432/dual_resnet.py", line 395, in resnet101
    model = load_dualpath_model(model, pretrained_model)
  File "/mnt/txf/codes/SA-Gate/RGBD_Semantic_Segmentation_PyTorch/model/SA-Gate.nyu.432/dual_resnet.py", line 304, in load_dualpath_model
    raw_state_dict = torch.load(model_file)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: pickle data was truncated
请问这个问题是数据有问题还是内存不足导致的？目前服务器只有两张卡，如果您有空的话，希望能够得到您的帮助，非常感谢！

**Comment by small-beebee** [comment]
谢谢，我已经解决了这个问题。

**Comment by changshuowang** [comment]
> 谢谢，我已经解决了这个问题。

@small-beebee 你好，我也遇到同样的问题，请问你是怎么解决的呢？

**Comment by charlesCXK** [comment]
@changshuowang  
Hi, I suspect that something is wrong with the model file.

**Comment by changshuowang** [comment]
> @changshuowang
> Hi, I suspect that something is wrong with the model file.

  @charlesCXK 谢谢作者回复，我是下载该仓库的文件直接运行的，我报的bug如下所示：

(rgbd) xxx@ubuntu01:~/RGBD_Semantic_Segmentation_PyTorch/model/SA-Gate.nyu$ export NGPUS=1
(rgbd) xxx@ubuntu01:~/RGBD_Semantic_Segmentation_PyTorch/model/SA-Gate.nyu$ python -m torch.distributed.launch --nproc_per_node=$NGPUS train.py
14 06:07:03 PyTorch Version 1.0.0, Furnace Version 0.1.1
Warning:  using Python fallback for SyncBatchNorm, possibly because apex was installed without --cuda_ext.  The exception raised when attempting to import the cuda backend was:  /home/xxx/.conda/envs/rgbd/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/syncbn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration
14 06:07:04 WRN A exception occurred during Engine initialization, give up running process
Traceback (most recent call last):
  File "train.py", line 64, in <module>
    norm_layer=BatchNorm2d)
  File "/home/xxx/RGBD_Semantic_Segmentation_PyTorch/model/SA-Gate.nyu/network.py", line 33, in __init__
    deep_stem=True, stem_width=64)
  File "/home/xxxRGBD_Semantic_Segmentation_PyTorch/model/SA-Gate.nyu/dual_resnet.py", line 395, in resnet101
    model = load_dualpath_model(model, pretrained_model)
  File "/home/xxx/RGBD_Semantic_Segmentation_PyTorch/model/SA-Gate.nyu/dual_resnet.py", line 304, in load_dualpath_model
    raw_state_dict = torch.load(model_file)
  File "/home/xxx/.conda/envs/rgbd/lib/python3.6/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/xxx/.conda/envs/rgbd/lib/python3.6/site-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: pickle data was truncated
但是目前还不知道哪里出错。

**Comment by charlesCXK** [comment]
According to [this link](https://blog.csdn.net/zhen15652/article/details/114260526), I suspect that your batch size is too large. Maybe you could (1) try to use a smaller batch size; (2) re-download the model file. 
Besides, your Apex is not installed normally and the SyncBN is invalid.
`Warning: using Python fallback for SyncBatchNorm, possibly because apex was installed without --cuda_ext. `

**Comment by changshuowang** [comment]
明天我改一下，感谢作者提供解决意见


---Original---
From: &quot;Chen ***@***.***&gt;
Date: Tue, Jun 15, 2021 01:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [charlesCXK/RGBD_Semantic_Segmentation_PyTorch] Error about data loading (#13)




 
According to this link, I suspect that your batch size is too large. Maybe you could try to use a smaller one.
 Besides, your Apex is not installed normally and the SyncBN is invalid.
 Warning: using Python fallback for SyncBatchNorm, possibly because apex was installed without --cuda_ext. 
 
&mdash;
